### ISSUE TITLE
Textures not working

### ISSUE THREAD

**Issue by ghost** [Sleaker/Cubed#3]
Please fix this

**Comment by Sleaker** [comment]
Not sure what you mean, the textures were working in the last version but the shaders require modern opengl and this is mostly just a sample for others to look at. If you are having a specific issue and need help tracking it down I might be able to help but I need more than just 'textures not working'

**Comment by ghost** [comment]
Sorry for the lack of detail, I am creating a Voxel game like Minecraft in jMonkeyEngine and was looking for a project with Greedy Mesh to implement, and your code is perfect for me, but when I test, the textures are white. I do not want to make the game depends on OpenGL, GLSL or advanced PC, so please give me some help on how to make your textures operating without OpenGL!

**Comment by Dimalenus** [comment]
I can post a screenshot here

**Comment by ghost** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/16289211/13894986/cd0b4b06-ed4c-11e5-91d3-bb369ffca31f.png)
![sem tituldo](https://cloud.githubusercontent.com/assets/16289211/13894987/cd458d98-ed4c-11e5-9895-4d542ebe0d5d.png)

**Comment by ghost** [comment]
Any help?

**Comment by Sleaker** [comment]
I'm having a hard time understanding your statements as they don't line up with the requirements of the software you're developing with. openGL is a requirement to even be using JME, my adjustments to the shader for greedy meshing require OpenGL 3.3 at the minimum. So you are going to have limitations there. I can't tell you how to make the textures work without openGL since it's built into the game engine and you can't actually do any drawing in JME without using openGL..  I can't really help much beyond this as it sounds like you're needing some basic tutorials for using JME which I can't give you other than referring you to the JMe forums.
